/*
 * Copyright (c) 2026 Thanford. All rights reserved.
 *
 * Proprietary Glyphew component. Not licensed under the MPL 2.0 that
 * covers the surrounding Wolvic files.
 */
package com.thanford.glyphew.home;

import androidx.annotation.NonNull;

/**
 * Hardcoded site catalog for the homepage.
 *
 * Brand colors are precomputed at build time by tools/precompute-brand-colors.mjs
 * and embedded here. Re-run the script when the site list changes.
 *
 * Icon paths use the bundled PNG filenames at assets/glyphew/icons/<domain>.png.
 * The Java layer does not need to know the full asset path — homepage.js resolves
 * relative paths against its own document base.
 */
public final class HomeCatalog {

    private HomeCatalog() {}

    /**
     * Returns the full catalog as a JSON string matching the bridge schema:
     * [{id, label, editable:false, sites:[{url,domain,iconPath,brandColor}]}]
     *
     * Brand colors and icon paths are embedded inline; no file I/O at runtime.
     */
    @NonNull
    public static String json() {
        return CATALOG_JSON;
    }

    // Generated by tools/precompute-brand-colors.mjs.
    // Format: JSON array, compact (no whitespace), ASCII-safe.
    private static final String CATALOG_JSON =
        "[" +
        "{\"id\":\"news\",\"label\":\"News\",\"editable\":false,\"sites\":[" +
            "{\"url\":\"https://news.google.com\",\"domain\":\"Google News\",\"iconPath\":\"icons/google.png\",\"brandColor\":\"#4285F4\"}," +
            "{\"url\":\"https://www.bbc.com\",\"domain\":\"BBC\",\"iconPath\":\"icons/bbc.png\",\"brandColor\":\"#BB1919\"}," +
            "{\"url\":\"https://www.reuters.com\",\"domain\":\"Reuters\",\"iconPath\":\"icons/reuters.png\",\"brandColor\":\"#FF8000\"}," +
            "{\"url\":\"https://apnews.com\",\"domain\":\"AP News\",\"iconPath\":\"icons/apnews.png\",\"brandColor\":\"#CC0000\"}" +
        "]}," +
        "{\"id\":\"search\",\"label\":\"Search\",\"editable\":false,\"sites\":[" +
            "{\"url\":\"https://www.google.com\",\"domain\":\"Google\",\"iconPath\":\"icons/google.png\",\"brandColor\":\"#4285F4\"}," +
            "{\"url\":\"https://www.bing.com\",\"domain\":\"Bing\",\"iconPath\":\"icons/bing.png\",\"brandColor\":\"#008373\"}," +
            "{\"url\":\"https://duckduckgo.com\",\"domain\":\"DuckDuckGo\",\"iconPath\":\"icons/duckduckgo.png\",\"brandColor\":\"#DE5833\"}," +
            "{\"url\":\"https://search.brave.com\",\"domain\":\"Brave\",\"iconPath\":\"icons/brave.png\",\"brandColor\":\"#FB542B\"}" +
        "]}," +
        "{\"id\":\"social\",\"label\":\"Social\",\"editable\":false,\"sites\":[" +
            "{\"url\":\"https://www.reddit.com\",\"domain\":\"Reddit\",\"iconPath\":\"icons/reddit.png\",\"brandColor\":\"#FF4500\"}," +
            "{\"url\":\"https://www.twitter.com\",\"domain\":\"X / Twitter\",\"iconPath\":\"icons/twitter.png\",\"brandColor\":\"#1DA1F2\"}," +
            "{\"url\":\"https://www.mastodon.social\",\"domain\":\"Mastodon\",\"iconPath\":\"icons/mastodon.png\",\"brandColor\":\"#6364FF\"}," +
            "{\"url\":\"https://discord.com/app\",\"domain\":\"Discord\",\"iconPath\":\"icons/discord.png\",\"brandColor\":\"#5865F2\"}" +
        "]}," +
        "{\"id\":\"video\",\"label\":\"Video\",\"editable\":false,\"sites\":[" +
            "{\"url\":\"https://www.youtube.com\",\"domain\":\"YouTube\",\"iconPath\":\"icons/youtube.png\",\"brandColor\":\"#FF0000\"}," +
            "{\"url\":\"https://www.twitch.tv\",\"domain\":\"Twitch\",\"iconPath\":\"icons/twitch.png\",\"brandColor\":\"#9146FF\"}," +
            "{\"url\":\"https://vimeo.com\",\"domain\":\"Vimeo\",\"iconPath\":\"icons/vimeo.png\",\"brandColor\":\"#1AB7EA\"}," +
            "{\"url\":\"https://www.netflix.com\",\"domain\":\"Netflix\",\"iconPath\":\"icons/netflix.png\",\"brandColor\":\"#E50914\"}" +
        "]}," +
        "{\"id\":\"shopping\",\"label\":\"Shopping\",\"editable\":false,\"sites\":[" +
            "{\"url\":\"https://www.amazon.com\",\"domain\":\"Amazon\",\"iconPath\":\"icons/amazon.png\",\"brandColor\":\"#FF9900\"}," +
            "{\"url\":\"https://www.ebay.com\",\"domain\":\"eBay\",\"iconPath\":\"icons/ebay.png\",\"brandColor\":\"#E53238\"}," +
            "{\"url\":\"https://www.etsy.com\",\"domain\":\"Etsy\",\"iconPath\":\"icons/etsy.png\",\"brandColor\":\"#F1641E\"}," +
            "{\"url\":\"https://www.bestbuy.com\",\"domain\":\"Best Buy\",\"iconPath\":\"icons/bestbuy.png\",\"brandColor\":\"#0046BE\"}" +
        "]}," +
        "{\"id\":\"tools\",\"label\":\"Tools\",\"editable\":false,\"sites\":[" +
            "{\"url\":\"https://github.com\",\"domain\":\"GitHub\",\"iconPath\":\"icons/github.png\",\"brandColor\":\"#24292F\"}," +
            "{\"url\":\"https://stackoverflow.com\",\"domain\":\"Stack Overflow\",\"iconPath\":\"icons/stackoverflow.png\",\"brandColor\":\"#F48024\"}," +
            "{\"url\":\"https://www.wikipedia.org\",\"domain\":\"Wikipedia\",\"iconPath\":\"icons/wikipedia.png\",\"brandColor\":\"#3366CC\"}," +
            "{\"url\":\"https://translate.google.com\",\"domain\":\"Translate\",\"iconPath\":\"icons/google.png\",\"brandColor\":\"#4285F4\"}" +
        "]}" +
        "]";
}
